# TODO - fix dagger
#java_library(
#    name = "example",
#    srcs = glob(["*.java"]),
#    visibility = ["//visibility:public"],
#    deps = [
#        "//src/main/java/com/gautam/package2",
#        "@com_google_dagger//:dagger_with_compiler",
#        "@third_party//3rdparty/jvm/com/google/guava",
#    ],
#)
