java_binary(
    name = "ExampleBenchmark",
    main_class = "org.openjdk.jmh.Main",
    srcs = ["ExampleBenchmark.java"],
    deps = [
        "//src/main/java/com/example/package1",
        "//src/main/java/com/example/package2",
        "//src/main/java/com/example/rest",
        "//third_party:jmh",
        "@maven//:com_google_guava_guava",
    ],
)
