java_binary(
    name = "java_formatter_bin",
    main_class = "com.google.googlejavaformat.java.Main",
    runtime_deps = ["@third_party//3rdparty/jvm/com/google/googlejavaformat:google_java_format"],
)
