java_library(
    name = "package1",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/java/com/example/package2",
        "@maven//:com_google_guava_guava",
    ],
)
