java_library(
    name = "package1",
    srcs = glob(["*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        "//src/main/java/com/gautam/package2",
        "@third_party//3rdparty/jvm/com/google/guava",
    ],
)
